version: '3.8'

services:
  db:
    image: 'postgres:14.2'
    restart: always
    environment:
      POSTGRES_DB: meetings
      POSTGRES_USER: meetings
      POSTGRES_PASSWORD: meetings
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

volumes:
  db_data:
